# Trabalho 2 - SVD e recomendação de filmes.         Nícolas Hecker Silva         RA: 186132

A primeira parte importante desse trabalho é baixar as dependencias necessárias usando pip, caso a máquina não as possua. Para isso usamos o código abaixo:

In [ ]:
# instalar dependencias
!pip install pandas
!pip install jax
!pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
!pip install scikit-learn
!pip install matplotlib


# Implementação do SVD:

Através das funções de autovetores e autovalores e comparando com a função própria.

primeiro função própria do jax e do numpy

In [19]:
import jax.numpy as jnp

matrix = jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

U, S, VT = jnp.linalg.svd(matrix, full_matrices=True)

print("Autovetores U:\n", U)
print("Autovalores:\n",S)
print("Autovetores VT:\n",VT)

print("\n================================== Agora com numpy ===========================================\n")
import numpy as np
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
Un, Sn, VTn = np.linalg.svd(matriz, full_matrices=True)

print("Autovetores U:\n", Un)
print("Autovalores:\n",Sn)
print("Autovetores VT:\n",VTn)


Autovetores U:
 [[ 0.14087664  0.82471395  0.46999776  0.2812515 ]
 [ 0.34394628  0.42626432 -0.8362956  -0.02468661]
 [ 0.5470158   0.02781341  0.2625992  -0.7943813 ]
 [ 0.75008535 -0.37063694  0.10369895  0.5378164 ]]
Autovalores:
 [2.5462400e+01 1.2906601e+00 2.8028271e-07]
Autovetores VT:
 [[ 0.5045332   0.5745157   0.64449817]
 [-0.7607754  -0.05714092  0.64649487]
 [ 0.40824872 -0.81649655  0.40824792]]

================================== Agora com numpy ===========================================

Autovetores U:
 [[-0.14087668 -0.82471435  0.54704904 -0.02715407]
 [-0.34394629 -0.42626394 -0.70915928  0.4439517 ]
 [-0.54701591 -0.02781353 -0.22282857 -0.80644121]
 [-0.75008553  0.37063688  0.38493881  0.38964357]]
Autovalores:
 [2.54624074e+01 1.29066168e+00 1.80972823e-15]
Autovetores VT:
 [[-0.50453315 -0.5745157  -0.64449826]
 [ 0.76077568  0.05714052 -0.64649464]
 [-0.40824829  0.81649658 -0.40824829]]


In [16]:
SL = matrix @ matrix.T
SR = matrix.T @ matrix

print("Matriz esquerda:\n",SL)
print("Matriz direita:\n",SR)
    
s1,u = jnp.linalg.eigh(SL)
s2,v = jnp.linalg.eigh(SR)

# se módulo menor que 1e-5, considera zero. Também tira a raiz quadrada
s1 = jnp.where(jnp.abs(s1) < 1e-5, 0, s1)**0.5
s2 = jnp.where(jnp.abs(s2) < 1e-5, 0, s2)**0.5

print("Autovetores esquerda:\n",u)
print("Autovetores direita:\n",v)
print("Autovalores S1:\n",s1)
print("Autovalores S2:\n",s2)

Matriz esquerda:
 [[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]
Matriz direita:
 [[166 188 210]
 [188 214 240]
 [210 240 270]]
Autovetores esquerda:
 [[-0.34394345  0.42626652  0.82471424  0.14087665]
 [ 0.14087537 -0.8247139   0.42626527  0.34394637]
 [ 0.7500866   0.37063494  0.02781123  0.5470159 ]
 [-0.5470166   0.02781428 -0.37063578  0.7500856 ]]
Autovetores direita:
 [[ 0.40824673 -0.7607764   0.50453305]
 [-0.8164966  -0.05713892  0.5745157 ]
 [ 0.4082495   0.6464938   0.6444983 ]]
Autovalores S1:
 [ 0.         0.         1.2906629 25.46241  ]
Autovalores S2:
 [ 0.         1.2906607 25.462406 ]


In [35]:
# obtem os indices para que ordenam os autovalores
idx1 = jnp.argsort(s1)[::-1]
idx2 = jnp.argsort(s2)[::-1]

# ordena os autovalores e autovetores
s1 = s1[idx1]
s2 = s2[idx2]

u = u[:,idx1]
v = v[:,idx2]

print("Autovetores esquerda ordenados:\n",u)
print("Autovetores direita ordenados transposto:\n",v.T)
print("Autovalores S1 ordenados:\n",s1)
print("Autovalores S2 ordenados:\n",s2)

print("\n ==================== comapração com SVD nativo =====================\n")

print("Autovetores U:\n", U)
print("Autovalores:\n",jnp.where(jnp.abs(S) < 1e-5, 0, S))
print("Autovetores VT:\n",VT)



Autovetores esquerda ordenados:
 [[ 0.14087665  0.82471424 -0.34394345  0.42626652]
 [ 0.34394637  0.42626527  0.14087537 -0.8247139 ]
 [ 0.5470159   0.02781123  0.7500866   0.37063494]
 [ 0.7500856  -0.37063578 -0.5470166   0.02781428]]
Autovetores direita ordenados transposto:
 [[ 0.50453305  0.5745157   0.6444983 ]
 [-0.7607764  -0.05713892  0.6464938 ]
 [ 0.40824673 -0.8164966   0.4082495 ]]
Autovalores S1 ordenados:
 [25.46241    1.2906629  0.         0.       ]
Autovalores S2 ordenados:
 [25.462406   1.2906607  0.       ]

 ==================== comapração com SVD nativo =====================

Autovetores U:
 [[ 0.14087664  0.82471395  0.46999776  0.2812515 ]
 [ 0.34394628  0.42626432 -0.8362956  -0.02468661]
 [ 0.5470158   0.02781341  0.2625992  -0.7943813 ]
 [ 0.75008535 -0.37063694  0.10369895  0.5378164 ]]
Autovalores:
 [25.4624     1.2906601  0.       ]
Autovetores VT:
 [[ 0.5045332   0.5745157   0.64449817]
 [-0.7607754  -0.05714092  0.64649487]
 [ 0.40824872 -0.81649655  0.

In [42]:
# get the dataset of https://files.grouplens.org/datasets/movielens/ml-100k.zip if not exists
import os
if not os.path.exists('dataset-t2/ml-100k'):
    !wget https://files.grouplens.org/datasets/movielens/ml-100k.zip
    !unzip ml-100k.zip -d dataset-t2/
    # remove the zip file
    !rm ml-100k.zip

--2024-10-02 16:01:10--  https://files.grouplens.org/datasets/movielens/ml-100k.zip
Resolvendo files.grouplens.org (files.grouplens.org)... 

/usr/lib/python3.12/pty.py:95: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()


128.101.65.152
Conectando-se a files.grouplens.org (files.grouplens.org)|128.101.65.152|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 4924029 (4,7M) [application/zip]
Salvando em: ‘ml-100k.zip’

ml-100k.zip         100%[===================>]   4,70M  2,34MB/s    em 2,0s    

2024-10-02 16:01:13 (2,34 MB/s) - ‘ml-100k.zip’ salvo [4924029/4924029]

Archive:  ml-100k.zip
   creating: dataset-t2/ml-100k/
  inflating: dataset-t2/ml-100k/allbut.pl  
  inflating: dataset-t2/ml-100k/mku.sh  
  inflating: dataset-t2/ml-100k/README  
  inflating: dataset-t2/ml-100k/u.data  
  inflating: dataset-t2/ml-100k/u.genre  
  inflating: dataset-t2/ml-100k/u.info  
  inflating: dataset-t2/ml-100k/u.item  
  inflating: dataset-t2/ml-100k/u.occupation  
  inflating: dataset-t2/ml-100k/u.user  
  inflating: dataset-t2/ml-100k/u1.base  
  inflating: dataset-t2/ml-100k/u1.test  
  inflating: dataset-t2/ml-100k/u2.base  
  inflating: dataset-t2/ml-100k/u2.test  
  infl

Os conjuntos preprocessados, possuem todos os sujeitos no treino. Entretanto isso não é interessante para a tarefa, uma vez que queremos prever as avaliacoes para um novo sujeito. Logo, precisamos fazer nosso próprio particionamento.

In [58]:
# carrega com pandas o dataset u1 separado por tabs
import pandas as pd

# carrega o dataset de avaliações
complete = pd.read_csv('dataset-t2/ml-100k/u.data', sep='\t', header=None)
complete.columns = ['user_id', 'movie_id', 'rating', 'timestamp']

complete


user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [71]:
# seleciona aleatoriamente 80% dos usuarios para treino e os demais para teste
np.random.seed(42)
users = complete.user_id.unique()
np.random.shuffle(users)
train_users = users[:int(0.8*len(users))]
test_users = users[int(0.8*len(users)):]
print("Numero de usuarios para treino:",len(train_users))
print("Numero de usuarios para teste:",len(test_users))

print(sorted(train_users)[:5])
print(sorted(test_users)[:5])

Numero de usuarios para treino: 754
Numero de usuarios para teste: 189
[np.int64(1), np.int64(2), np.int64(4), np.int64(5), np.int64(6)]
[np.int64(3), np.int64(13), np.int64(43), np.int64(45), np.int64(46)]


In [74]:
# com base nos train_users e test_users, separa os dados de treino e teste
train_raw = complete[complete.user_id.isin(train_users)]
test_raw = complete[complete.user_id.isin(test_users)]

print("Numero de avaliações para treino:",len(train_raw))
print("Numero de avaliações para teste:",len(test_raw))

Numero de avaliações para treino: 79186
Numero de avaliações para teste: 20814


In [76]:
train_raw

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
2           22       377       1  878887116
3          244        51       2  880606923
5          298       474       4  884182806
6          115       265       2  881171488
...        ...       ...     ...        ...
99993      913       209       2  881367150
99994      378        78       3  880056976
99996      716       204       5  879795543
99997      276      1090       1  874795795
99999       12       203       3  879959583

[79186 rows x 4 columns]

próximo a 80000 amostras

In [77]:
test_raw

user_id  movie_id  rating  timestamp
1          186       302       3  891717742
4          166       346       1  886397596
13         210        40       3  891035994
14         224        29       3  888104457
20         119       392       4  886176814
...        ...       ...     ...        ...
99987      660       229       2  891406212
99988      421       498       4  892241344
99989      495      1091       4  888637503
99995      880       476       3  880175444
99998       13       225       2  882399156

[20814 rows x 4 columns]

próximo a 20000 amostras

Agora constroi a tabelona

In [81]:
# cria a matriz de avaliações
# a linha da matriz de treino é o usuario, a coluna é o filme, e o valor é a avaliação. Se não houver avaliação, é NaN
train = train_raw.pivot(index='user_id', columns='movie_id', values='rating')
test = test_raw.pivot(index='user_id', columns='movie_id', values='rating')

print("Matriz de treino:",train.shape)
print("Matriz de teste:",test.shape)

Matriz de treino: (754, 1646)
Matriz de teste: (189, 1438)


In [82]:
train

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2          4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5          4.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
6          4.0   NaN   NaN   NaN   NaN   NaN   2.0   4.0   4.0   NaN  ...   
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN  ...   
940        NaN   NaN   NaN   2.0   NaN   NaN   4.0   5.0   3.0   NaN  ...   
941        5.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN  ...   
942        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
943        NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN  ...   

movie_id  1672  1673  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                               
1          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
6          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
940        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
941        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
942        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
943        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[754 rows x 1646 columns]

In [83]:
test

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
13         3.0   3.0   NaN   5.0   1.0   NaN   2.0   4.0   3.0   NaN  ...   
43         5.0   NaN   2.0   4.0   4.0   NaN   4.0   4.0   4.0   NaN  ...   
45         5.0   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN  ...   
46         NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN  ...   
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
902        5.0   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN  ...   
928        NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   5.0   NaN  ...   
931        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
936        4.0   NaN   4.0   NaN   NaN   5.0   4.0   NaN   4.0   NaN  ...   
937        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN  ...   

movie_id  1625  1627  1628  1639  1652  1653  1655  1661  1664  1674  
user_id                                                               
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
13         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
43         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
45         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
46         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
902        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
928        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
931        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
936        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
937        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[189 rows x 1438 columns]